"""add expired stats

Revision ID: 5c72d5b1f3aa
Revises: 9645d75efadf
Create Date: 2025-02-15 15:38:05.576668

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c72d5b1f3aa"
down_revision: Union[str, None] = "9645d75efadf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("servers", sa.Column("expired_stats", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("servers", "expired_stats")
    # ### end Alembic commands ###
