"""add node monotirings

Revision ID: 9645d75efadf
Revises: 4d6ca20ba71f
Create Date: 2025-01-18 04:56:14.450325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9645d75efadf"
down_revision: Union[str, None] = "4d6ca20ba71f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("servers", sa.Column("node_monitoring", sa.Boolean(), nullable=True))
    op.add_column("servers", sa.Column("node_restart", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("servers", "node_restart")
    op.drop_column("servers", "node_monitoring")
    # ### end Alembic commands ###
