name: Build and Test

on:
  pull_request:
    branches:
      - master

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-platform support
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            erfjab/holderbot:pr-${{ github.event.pull_request.number }}

      - name: Print Success Message
        if: success()
        run: |
          echo "✅ Docker Image built successfully!"
          echo "You can test it using the following command:"
          echo "docker run -it --rm erfjab/holderbot:pr-${{ github.event.pull_request.number }}"

      - name: Print Failure Message
        if: failure()
        run: |
          echo "❌ Docker Image build failed! Please check the logs for more details."